using System;
using System.Globalization;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;

namespace OscilloscopeControl.Capture
{
    /// <summary>
    /// Interaction logic for WaveformMemoryPanel.xaml
    /// Code-behind for the waveform capture and memory management user interface.
    /// 
    /// NOTE: The UI control properties are auto-generated by XAML via x:Name attributes.
    /// Do NOT declare them manually here to avoid CS0102 conflicts.
    /// </summary>
    public partial class WaveformMemoryPanel : UserControl
    {
        #region Constructor

        /// <summary>
        /// Initialize the waveform memory panel user control
        /// </summary>
        public WaveformMemoryPanel()
        {
            InitializeComponent();
            this.Loaded += WaveformMemoryPanel_Loaded;
        }

        #endregion

        #region Event Handlers

        /// <summary>
        /// Called when the user control is fully loaded
        /// </summary>
        private void WaveformMemoryPanel_Loaded(object sender, RoutedEventArgs e)
        {
            try
            {
                // Initialize default values for the controls
                // (Controls are auto-generated by XAML with x:Name attributes)
                InitializeDefaults();
            }
            catch (Exception ex)
            {
                // Log error if needed
                MessageBox.Show($"Error initializing UI controls: {ex.Message}", "UI Error", MessageBoxButton.OK, MessageBoxImage.Warning);
            }
        }

        #endregion

        #region Initialization

        /// <summary>
        /// Initialize default values for UI controls
        /// </summary>
        private void InitializeDefaults()
        {
            try
            {
                // Initialize channel selection
                if (ChannelSelectionComboBox != null)
                {
                    ChannelSelectionComboBox.Items.Clear();
                    ChannelSelectionComboBox.Items.Add("Channel 1");
                    ChannelSelectionComboBox.Items.Add("Channel 2");
                    ChannelSelectionComboBox.Items.Add("Both Channels");
                    ChannelSelectionComboBox.SelectedIndex = 0;
                }

                // Initialize waveform mode
                if (WaveformModeComboBox != null)
                {
                    WaveformModeComboBox.Items.Clear();
                    WaveformModeComboBox.Items.Add("Normal");
                    WaveformModeComboBox.Items.Add("Raw");
                    WaveformModeComboBox.Items.Add("Maximum");
                    WaveformModeComboBox.SelectedIndex = 0;
                }

                // Initialize waveform format
                if (WaveformFormatComboBox != null)
                {
                    WaveformFormatComboBox.Items.Clear();
                    WaveformFormatComboBox.Items.Add("Byte");
                    WaveformFormatComboBox.Items.Add("Word");
                    WaveformFormatComboBox.Items.Add("ASCII");
                    WaveformFormatComboBox.SelectedIndex = 0;
                }

                // Initialize filter channel
                if (FilterChannelComboBox != null)
                {
                    FilterChannelComboBox.Items.Clear();
                    FilterChannelComboBox.Items.Add("All Channels");
                    FilterChannelComboBox.Items.Add("Channel 1 Only");
                    FilterChannelComboBox.Items.Add("Channel 2 Only");
                    FilterChannelComboBox.SelectedIndex = 0;
                }

                // Initialize memory limit slider
                if (MemoryLimitSlider != null)
                {
                    MemoryLimitSlider.Minimum = 10;
                    MemoryLimitSlider.Maximum = 1000;
                    MemoryLimitSlider.Value = 100;
                }

                // Initialize status text
                if (MemoryStatusTextBlock != null)
                {
                    MemoryStatusTextBlock.Text = "Ready";
                }

                if (MemoryLimitTextBlock != null)
                {
                    MemoryLimitTextBlock.Text = "100";
                }
            }
            catch (Exception ex)
            {
                // Ignore initialization errors for missing controls
            }
        }

        #endregion

        #region Public Properties for Compatibility

        /// <summary>
        /// Indicates whether the panel is ready for capture operations
        /// </summary>
        public bool IsReadyForCapture => CaptureWaveformButton?.IsEnabled == true;

        /// <summary>
        /// Gets the number of items currently in the waveform list
        /// </summary>
        public int WaveformCount => StoredWaveformsListBox?.Items.Count ?? 0;

        #endregion

        // NOTE: All UI control properties (ChannelSelectionComboBox, WaveformModeComboBox, etc.)
        // are automatically generated by XAML when you use x:Name="ControlName" in the XAML file.
        // Do NOT declare them manually here - that causes CS0102 "already contains a definition" errors.
    }
}